org: hughescr
app: zoom-attendee-webhook
# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: Zoom-Attendee-Webhook

provider:
  name: aws
  # These values are defaults, and can be over-written in each function below
  architecture: arm64
  runtime: nodejs16.x
  memorySize: 256
  timeout: 10
  region: us-west-2
  versionFunctions: false

  deploymentBucket:
    name: ${ssm:/serverless/deploymentbucket/prefix}-${self:provider.region}
    blockPublicAccess: true

  environment:
    ZOOM_AUTHORIZATION_CODE: ${param:ZOOM_AUTHORIZATION_CODE}

  stackTags:
    Project: "PV Zoom Attendees"
    Organization: "Town of Portola Valley"

  logs:
    httpApi:
      format: >-
        {
        "requestTime":"$context.requestTime",
        "requestId":"$context.requestId",
        "apiId":"$context.apiId",
        "identity": {
        "sourceIp":"$context.identity.sourceIp",
        "userAgent":"$context.identity.userAgent"
        },
        "resourcePath":"$context.routeKey",
        "path":"$context.path",
        "httpMethod":"$context.httpMethod",
        "stage":"$context.stage",
        "status":"$context.status",
        "integrationStatus":"$context.integrationStatus",
        "integrationLatency":"$context.integrationLatency",
        "responseLatency":"$context.responseLatency",
        "responseLength":"$context.responseLength",
        "errorMessage":"$context.error.message",
        "format":"SLS_HTTP_API_LOG","version":"1.0.0"
        }

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - { Fn::GetAtt: [ PVWebinarAttendees, Arn ] }
            - Fn::Join:
              - /
              -
                - { Fn::GetAtt: [ PVWebinarAttendees, Arn ] }
                - index/*

package:
  patterns:
    - '!coverage/**'
    - '!reports/**'
    - '!.nyc_output/**'
    - '!*.sublime*'
    - '!package.json'
    - '!package-lock.json'
    - '!stryker.conf.js'
    - '!yarn.lock'
    - '!yarn-error.log'
    - '!node_modules/aws-sdk/**'
    - '!**/test/**'
    - '!**/tests/**'

plugins:
  - "@hughescr/serverless-plugin-git-version-json"
  - serverless-domain-manager
  - serverless-plugin-log-retention

custom:
  # Specify the path to where the git versioning plugin should write its output json file, relative to the root folder
  versionJSONFile: git_version.json

  logRetentionInDays: 30

  customDomain:
    http:
      domainName: pv-zooms.rungie.com
      autoDomain: true
      createRoute53Record: true
      createRoute53IPv6Record: true
      endpointType: regional
      apiType: http

functions:

  handleZoomWebhook:
    description: >
      Handle participant joined/left webhook posts from Zoom. Update DynamoDB table to track
      adding one attendance point for every join and decrementing for every leave.
    handler: index.handleZoomWebhook
    events:
      - httpApi: POST /hook
      - schedule:
          description: Scheduled ping to the lambda to keep it warm
          rate: rate(1 minute)
          enabled: true
          input:
            keep-alive: true

  handleListMeetings:
    description: >
      Read data from DynamoDB and list all meetings that have a non-zero participant count, as HTML with links to each meeting.
    handler: index.handleListMeetings
    events:
      - httpApi: GET /
      - schedule:
          description: Scheduled ping to the lambda to keep it warm
          rate: rate(1 minute)
          enabled: true
          input:
            keep-alive: true

  handleListParticipants:
    description: >
      Read data from DynamoDB for a given meeting ID and list all the participants in that meeting, as HTML.
    handler: index.handleListParticipants
    events:
      - httpApi: GET /meeting/{meeting_id}
      - schedule:
          description: Scheduled ping to the lambda to keep it warm
          rate: rate(1 minute)
          enabled: true
          input:
            keep-alive: true

resources:
  Resources:
    PVWebinarAttendees:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PVWebinarAttendees
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          # Meeting ID is numeric "object.id" and is the ID of the webinar
          - AttributeName: MeetingID
            AttributeType: N
          # The latest title "object.topic" of the webinar
          # - AttributeName: MeetingTitle
          #   AttributeType: S
          # The latest start time "object.start_time" of the webinar as YYYY-MM-DDTHH:MM:SSZ
          # - AttributeName: MeetingStartTime
          #   AttributeType: S
          # The latest scheduled meeting duration "object.duration" of the webinar as a number of minutes
          # - AttributeName: MeetingDuration
          #   AttributeType: N
          # The latest name "object.participant.user_name" of the participant
          # - AttributeName: ParticipantName
          #   AttributeType: S
          # The latest email "object.participant.email" of the participant or "" if unknown
          # - AttributeName: ParticipantEmail
          #   AttributeType: S
          # ParticipantID is a string "object.participant.id" which is unique to this user across multiple logins, or the phone number for call-in users.
          - AttributeName: ParticipantID
            AttributeType: S
          # Times are stored as YYYY-MM-DDTHH:MM:SSZ from "object.participant.join_time"
          # - AttributeName: JoinTimes
          #   AttributeType: SS
          # Times are stored as YYYY-MM-DDTHH:MM:SSZ from "object.participant.leave_time"
          # - AttributeName: LeaveTimes
          #   AttributeType: SS
          # ParticipantSessionID is numeric "participant.user_id" and gets a new one issued for each login
          # - AttributeName: ParticipantSessionIds
          #   AttributeType: NS
          # ParticipationCount is calculated as number of joins minus number of leaves
          - AttributeName: ParticipationCount
            AttributeType: N
          # LastUpdatedAt is timestamp that this record was last modified as YYYY-MM-DDTHH:MM:SSZ
          - AttributeName: LastUpdatedAt
            AttributeType: S
        KeySchema:
          - AttributeName: MeetingID
            KeyType: HASH
          - AttributeName: ParticipantID
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: MeetingID-LastUpdatedAt
            KeySchema:
              - AttributeName: MeetingID
                KeyType: HASH
              - AttributeName: LastUpdatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - MeetingTitle
                - MeetingStartTime
                - MeetingDuration
                - ParticipationCount
          - IndexName: MeetingID-ParticipationCount
            KeySchema:
              - AttributeName: MeetingID
                KeyType: HASH
              - AttributeName: ParticipationCount
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - MeetingTitle
                - MeetingStartTime
                - MeetingDuration
                - ParticipantName
                - ParticipantEmail
                - JoinTimes
                - LeaveTimes
