name: Bug report
description: Create a report to help us improve
title: "[BUG] <insert short summary here>"
labels: [bug, triage]

body:

- type: markdown
  attributes:
    value: "###### Please fill in a short title above that summarizes the problem in a few words"

- type: input
  attributes:
    label: App version
    description: Please provide the version of the app you're using when you experience this bug. The version number is in the bottom-left corner of every screen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Current behavior
    description: A description of what you're experiencing, including screenshots if you have them
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: If you were expecting something else to happen, what were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce
    description: If you can reproduce this behavior, what steps do you need to go through?
    placeholder: |-
        1. Open browser; 
        2. Go to URL; 
        3. Click button XYZ (screenshots helpful); 
        4. See error...
  validations:
    required: false

- type: dropdown
  attributes:
    label: Prevalence
    description: How often do you encounter this bug?
    multiple: false
    options:
      - All the time
      - Sometimes yes, other times no
      - I've only seen it once or twice
      - The bug is purely hypothetical

- type: dropdown
  attributes:
    label: Web browser
    description: With which web browser(s) have you seen this bug?
    multiple: true
    options:
      - Edge
      - Chrome
      - Safari
      - Firefox
      - Other

- type: dropdown
  attributes:
    label: Operating system
    description: On which OS(es) have you seen this bug?
    multiple: true
    options:
      - Windows
      - Mac laptop/desktop
      - Linux
      - iPhone/iPad
      - Android
      - Other

- type: textarea
  attributes:
    label: Additional context
    description: Anything else we need to know about the problem?
  validations:
    required: false
